import { Ionicons } from "@expo/vector-icons";
import { useNavigation } from "@react-navigation/native";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { useGetMyGroupsQuery } from "../api/mobileApi";
import { Screen } from "../components/Screen";
import { persistLogout } from "../store/authSlice";
import { useAppDispatch, useAppSelector } from "../store/hooks";
import { colors } from "../theme";

const serviceItems = [{ label: "\uc21c\uc704", icon: "podium-outline", target: "Ranking" }, { label: "\uc774\uc6a9\ubc29\ubc95", icon: "book-outline", target: "Guide" }, { label: "\uc694\uae08\uc81c", icon: "card-outline", target: "Pricing" }, { label: "\ud6c4\uc6d0\ud558\uae30", icon: "heart-outline", target: "Donate" }] as const;
const informationItems = [{ label: "\uacf5\uc9c0\uc0ac\ud56d", icon: "megaphone-outline", target: "Notice" }, { label: "\uc790\uc8fc \ubb3b\ub294 \uc9c8\ubb38", icon: "help-circle-outline", target: "Faq" }, { label: "1:1 \ubb38\uc758", icon: "chatbubbles-outline", target: "Inquiry" }, { label: "\ucc44\ud305 \ubb38\uc758", icon: "chatbubble-ellipses-outline", target: "SupportChat" }] as const;
const policyItems = [{ label: "\uc774\uc6a9\uc57d\uad00", icon: "document-text-outline", target: "Terms" }, { label: "\uac1c\uc778\uc815\ubcf4 \ucc98\ub9ac\ubc29\uce68", icon: "lock-closed-outline", target: "Privacy" }] as const;

export function MyPageScreen() {
  const navigation = useNavigation<any>(); const dispatch = useAppDispatch(); const user = useAppSelector((state) => state.auth.user); const preferredGroupId = useAppSelector((state) => state.app.preferredGroupId); const groups = useGetMyGroupsQuery().data?.groups ?? []; const group = groups.find((item) => item.id === preferredGroupId) ?? groups[0];
  const roleLabel = group?.role === "owner" ? "\ub9ac\ub354" : group?.role === "admin" ? "\uc6b4\uc601\uc9c4" : group ? "\ud68c\uc6d0" : null;
  const logout = () => Alert.alert("\ub85c\uadf8\uc544\uc6c3", "\ub85c\uadf8\uc544\uc6c3 \ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?", [{ text: "\ucde8\uc18c", style: "cancel" }, { text: "\ub85c\uadf8\uc544\uc6c3", style: "destructive", onPress: () => dispatch(persistLogout()) }]);
  return <Screen contentStyle={styles.screen}><View style={styles.titleRow}><Text style={styles.pageTitle}>\ub9c8\uc774\ud398\uc774\uc9c0</Text><Pressable onPress={() => navigation.navigate("Settings")}><Ionicons name="settings-outline" size={26} color={colors.text} /></Pressable></View><View style={styles.profile}><View style={styles.grow}><View style={styles.nameRow}><Text style={styles.name}>{user?.name ?? user?.email ?? "\uc0ac\uc6a9\uc790"}\ub2d8</Text>{roleLabel ? <Text style={styles.role}>{roleLabel}</Text> : null}</View><Text style={styles.profileSub}>\ubc18\uac00\uc6cc\uc694! \uc624\ub298\ub3c4 \uc6b0\ub9ac\ub9ac\uadf8\ub97c \uc990\uaca8\ubcf4\uc138\uc694.</Text>{group ? <Text style={styles.groupName}>\uc120\ud0dd \ud074\ub7fd \u00b7 {group.name}</Text> : null}</View><Pressable style={styles.editButton} onPress={() => navigation.navigate("ProfileEdit")}><Text style={styles.editText}>\uc815\ubcf4 \uc218\uc815</Text></Pressable></View><MenuSection title="\uc11c\ube44\uc2a4" items={serviceItems} onPress={(target) => navigation.navigate(target)} /><MenuSection title="\uc548\ub0b4" items={informationItems} onPress={(target) => navigation.navigate(target)} /><MenuSection title="\uc57d\uad00 \ubc0f \uc815\ucc45" items={policyItems} onPress={(target) => navigation.navigate(target)} /><Pressable onPress={logout}><Text style={styles.logout}>\ub85c\uadf8\uc544\uc6c3</Text></Pressable></Screen>;
}
function MenuSection({ title, items, onPress }: { title: string; items: ReadonlyArray<{ label: string; icon: keyof typeof Ionicons.glyphMap; target: string }>; onPress: (target: string) => void }) { return <View style={styles.sectionWrap}><Text style={styles.sectionLabel}>{title}</Text><View style={styles.menuCard}>{items.map((item, index) => <Pressable key={item.target} style={[styles.menuItem, index > 0 && styles.divider]} onPress={() => onPress(item.target)}><Ionicons name={item.icon} size={20} color={colors.muted} /><Text style={styles.menuText}>{item.label}</Text><Ionicons name="chevron-forward" size={20} color="#9CA3AF" /></Pressable>)}</View></View>; }
const styles = StyleSheet.create({ screen: { backgroundColor: "#fff" }, titleRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, pageTitle: { color: colors.text, fontSize: 24, fontWeight: "900" }, profile: { flexDirection: "row", alignItems: "center", gap: 12, padding: 20, borderRadius: 12, backgroundColor: "#F5F5F5" }, grow: { flex: 1 }, nameRow: { flexDirection: "row", alignItems: "center", gap: 8 }, name: { color: colors.text, fontSize: 18, fontWeight: "900" }, role: { color: "#4F46E5", backgroundColor: "#EEF2FF", overflow: "hidden", borderRadius: 999, paddingHorizontal: 7, paddingVertical: 3, fontSize: 10, fontWeight: "800" }, profileSub: { color: colors.muted, fontSize: 12, marginTop: 5 }, groupName: { color: colors.primary, fontSize: 11, fontWeight: "700", marginTop: 5 }, editButton: { paddingHorizontal: 12, paddingVertical: 7, borderRadius: 8, borderWidth: 1, borderColor: colors.border, backgroundColor: "#fff" }, editText: { color: colors.text, fontSize: 11, fontWeight: "800" }, sectionWrap: { gap: 8 }, sectionLabel: { color: "#9CA3AF", fontSize: 11, fontWeight: "800" }, menuCard: { overflow: "hidden", borderRadius: 12, backgroundColor: "#F5F5F5" }, menuItem: { minHeight: 54, flexDirection: "row", alignItems: "center", gap: 14, paddingHorizontal: 16 }, divider: { borderTopWidth: 1, borderTopColor: "#E5E7EB" }, menuText: { flex: 1, color: colors.text, fontSize: 14, fontWeight: "700" }, logout: { color: "#9CA3AF", fontSize: 13, paddingVertical: 8 } });
