ALTER TABLE groups ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS address_detail TEXT;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION;
