import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, Box, Chip, Pagination, Table, TableBody, TableCell, TableHead, TableRow, Typography } from "@mui/material";

const API = import.meta.env.VITE_API_BASE_URL ?? "/api";
type History = { id: string; kind: "settlement" | "receipt_scan"; status: string; created_at: string; league_name: string; league_code: string; user_name: string | null; round_no: number | null; item_count: number; receipt_total: number | null; recognized_total: number | null; difference: number | null; error_message: string | null };
const money = (value: number | null) => value == null ? "-" : `${Number(value).toLocaleString("ko-KR")}원`;

export default function AdminSettlementPage() {
  const token = localStorage.getItem("admin_token") ?? "";
  const headers = useMemo(() => ({ Authorization: `Bearer ${token}` }), [token]);
  const [rows, setRows] = useState<History[]>([]); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [error, setError] = useState("");
  const load = useCallback(async () => { try { const response = await fetch(`${API}/admin/settlements/history?page=${page}&limit=30`, { headers }); const result = await response.json(); if (!response.ok) throw new Error("정산 내역을 불러오지 못했습니다."); setRows(result.history ?? []); setTotal(result.total ?? 0); setError(""); } catch (cause) { setError((cause as Error).message); } }, [headers, page]);
  useEffect(() => { void load(); }, [load]);
  return <Box sx={{ p: 3 }}><Typography variant="h6" fontWeight={900} mb={0.5}>정산 내역</Typography><Typography color="text.secondary" fontSize={13} mb={2.5}>저장된 뒤풀이 정산과 영수증 인식 시도를 확인합니다.</Typography>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Box sx={{ overflowX: "auto" }}><Table size="small"><TableHead><TableRow><TableCell>일시</TableCell><TableCell>구분</TableCell><TableCell>상태</TableCell><TableCell>리그</TableCell><TableCell>차수</TableCell><TableCell>요청자</TableCell><TableCell align="right">품목/인원</TableCell><TableCell align="right">영수증/총액</TableCell><TableCell align="right">인식/정산액</TableCell><TableCell align="right">차이</TableCell></TableRow></TableHead><TableBody>{rows.map((row) => <TableRow key={`${row.kind}-${row.id}`} hover><TableCell sx={{ whiteSpace: "nowrap" }}>{new Date(row.created_at).toLocaleString("ko-KR")}</TableCell><TableCell>{row.kind === "receipt_scan" ? "영수증 인식" : "정산 저장"}</TableCell><TableCell><Chip size="small" label={row.status === "success" ? "성공" : row.status === "failed" ? "실패" : row.status === "processing" ? "처리 중" : "저장"} color={row.status === "failed" ? "error" : row.status === "success" || row.status === "saved" ? "success" : "default"} /></TableCell><TableCell>{row.league_name}<Typography component="span" color="text.secondary" fontSize={11}> · {row.league_code}</Typography></TableCell><TableCell>{row.round_no ? `${row.round_no}차` : "-"}</TableCell><TableCell>{row.user_name || "-"}</TableCell><TableCell align="right">{row.item_count ?? 0}</TableCell><TableCell align="right">{money(row.receipt_total)}</TableCell><TableCell align="right">{money(row.recognized_total)}</TableCell><TableCell align="right" title={row.error_message || ""}>{row.error_message ? row.error_message : money(row.difference)}</TableCell></TableRow>)}</TableBody></Table></Box>{!rows.length && !error && <Typography color="text.secondary" textAlign="center" py={6}>쌓인 정산 내역이 없습니다.</Typography>}<Pagination count={Math.max(1, Math.ceil(total / 30))} page={page} onChange={(_event, value) => setPage(value)} sx={{ mt: 2, display: "flex", justifyContent: "center" }} /></Box>;
}
