import {useCallback,useEffect,useState} from "react";
import {Alert,Box,Button,Chip,Dialog,DialogActions,DialogContent,DialogTitle,MenuItem,Stack,Switch,Table,TableBody,TableCell,TableHead,TableRow,TextField,Typography} from "@mui/material";
const API=import.meta.env.VITE_API_BASE_URL??"/api";
const TYPES:Record<string,string>={FREE_MONTHS:"N개월 무료 이용권",PERCENT_DISCOUNT:"N개월 할인권",LEAGUE_CREATE:"리그 생성 N회권",VISION_SCAN:"사진 인식 N회권",DRAW_CREATE:"추첨 생성 N회권"};
type Plan={code:string;name:string}; type Use={id:number;name:string;email:string;redeemed_at:string;clubs:{id:string;name:string}[]};
type Coupon={id:string;code:string;name:string;type:string;value:number;plan_code:string|null;duration_months:number|null;valid_from:string;valid_until:string;is_active:boolean;distribution_type:string;max_redemptions:number|null;redemption_count:number;redemptions:Use[]};
const blank={name:"",type:"LEAGUE_CREATE",value:1,planCode:"",durationMonths:1,validFrom:new Date().toISOString().slice(0,10),validUntil:"",quantity:1,distributionType:"SINGLE",customCode:"",maxRedemptions:""};
export default function AdminCouponPage(){
 const token=localStorage.getItem("admin_token")??"",headers={"Content-Type":"application/json",Authorization:`Bearer ${token}`};
 const [rows,setRows]=useState<Coupon[]>([]),[plans,setPlans]=useState<Plan[]>([]),[search,setSearch]=useState(""),[open,setOpen]=useState(false),[detail,setDetail]=useState<Coupon|null>(null),[form,setForm]=useState(blank),[error,setError]=useState("");
 const load=useCallback(async()=>{const r=await fetch(`${API}/admin/coupons?search=${encodeURIComponent(search)}`,{headers}),d=await r.json();r.ok?setRows(d.coupons??[]):setError("목록을 불러오지 못했습니다.");},[search]);
 useEffect(()=>{void load();},[load]); useEffect(()=>{fetch(`${API}/admin/pricing-plans`,{headers}).then(r=>r.json()).then(d=>setPlans(d.plans??[]));},[]);
 const set=(key:string,value:unknown)=>setForm(f=>({...f,[key]:value}));
 const save=async()=>{setError("");const r=await fetch(`${API}/admin/coupons`,{method:"POST",headers,body:JSON.stringify({...form,maxRedemptions:form.maxRedemptions||null,validFrom:new Date(`${form.validFrom}T00:00:00+09:00`).toISOString(),validUntil:new Date(`${form.validUntil}T23:59:59+09:00`).toISOString()})});const d=await r.json();if(!r.ok){setError(d.error==="DUPLICATE_CODE"?"이미 사용 중인 쿠폰번호입니다.":"입력 내용을 확인해 주세요.");return;}setOpen(false);setForm(blank);await load();};
 const remove=async(c:Coupon)=>{if(confirm(`${c.code} 쿠폰을 삭제하시겠습니까?`)){await fetch(`${API}/admin/coupons/${c.id}`,{method:"DELETE",headers});await load();}};
 const toggle=async(c:Coupon)=>{await fetch(`${API}/admin/coupons/${c.id}`,{method:"PATCH",headers,body:JSON.stringify({isActive:!c.is_active})});await load();};
 const benefit=(c:Coupon)=>c.type==="FREE_MONTHS"?`${plans.find(p=>p.code===c.plan_code)?.name??c.plan_code} ${c.value}개월 무료`:c.type==="PERCENT_DISCOUNT"?`${plans.find(p=>p.code===c.plan_code)?.name??c.plan_code} ${c.duration_months??1}개월간 ${c.value}% 할인`:`${TYPES[c.type]} · ${c.value}회`;
 return <Box sx={{p:3}}><Stack direction="row" justifyContent="space-between" mb={2}><Box><Typography fontSize={20} fontWeight={900}>쿠폰 관리</Typography><Typography fontSize={13} color="text.secondary">1회용 쿠폰과 SNS 공개용 오픈 쿠폰을 관리합니다.</Typography></Box><Button variant="contained" onClick={()=>setOpen(true)}>쿠폰 생성</Button></Stack>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<TextField fullWidth size="small" placeholder="쿠폰번호, 쿠폰명, 이메일 검색" value={search} onChange={e=>setSearch(e.target.value)} sx={{mb:2}}/>
 <Table size="small"><TableHead><TableRow><TableCell>쿠폰번호</TableCell><TableCell>발급</TableCell><TableCell>혜택</TableCell><TableCell>사용기한</TableCell><TableCell>상태 / 사용</TableCell><TableCell>관리</TableCell></TableRow></TableHead><TableBody>{rows.map(c=><TableRow key={c.id}><TableCell><b>{c.code}</b><br/>{c.name}</TableCell><TableCell><Chip size="small" label={c.distribution_type==="OPEN"?"오픈":"1회용"}/></TableCell><TableCell>{benefit(c)}</TableCell><TableCell>{new Date(c.valid_from).toLocaleDateString()} ~ {new Date(c.valid_until).toLocaleDateString()}</TableCell><TableCell><Chip size="small" color={c.is_active?"success":"error"} label={c.is_active?"사용 가능":"중지"}/><Button size="small" onClick={()=>setDetail(c)}>{c.redemption_count}명{c.max_redemptions?`/${c.max_redemptions}명`:""}</Button></TableCell><TableCell><Switch size="small" checked={c.is_active} onChange={()=>toggle(c)}/><Button color="error" size="small" onClick={()=>remove(c)}>삭제</Button></TableCell></TableRow>)}</TableBody></Table>
 <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>쿠폰 생성</DialogTitle><DialogContent><Stack gap={2} mt={1}><TextField select label="발급 방식" value={form.distributionType} onChange={e=>set("distributionType",e.target.value)}><MenuItem value="SINGLE">1회용 난수 쿠폰</MenuItem><MenuItem value="OPEN">SNS 공개용 오픈 쿠폰</MenuItem></TextField>{form.distributionType==="OPEN"&&<><TextField label="공개 쿠폰번호" value={form.customCode} onChange={e=>set("customCode",e.target.value)} helperText="한글·영문·숫자 사용 가능"/><TextField type="number" label="전체 사용 한도 (비우면 무제한)" value={form.maxRedemptions} onChange={e=>set("maxRedemptions",e.target.value)}/></>}<TextField label="쿠폰명" value={form.name} onChange={e=>set("name",e.target.value)}/><TextField select label="쿠폰 종류" value={form.type} onChange={e=>set("type",e.target.value)}>{Object.entries(TYPES).map(([v,l])=><MenuItem value={v} key={v}>{l}</MenuItem>)}</TextField>
 {["FREE_MONTHS","PERCENT_DISCOUNT"].includes(form.type)&&<TextField select label="적용 요금제" value={form.planCode} onChange={e=>set("planCode",e.target.value)}><MenuItem value="" disabled>요금제를 선택하세요</MenuItem>{plans.map(p=><MenuItem key={p.code} value={p.code}>{p.name}</MenuItem>)}</TextField>}{form.type==="FREE_MONTHS"&&<TextField type="number" label="무료 이용 개월 수" value={form.value} onChange={e=>set("value",Number(e.target.value))}/>} {form.type==="PERCENT_DISCOUNT"&&<><TextField type="number" label="할인 적용 개월 수" value={form.durationMonths} onChange={e=>set("durationMonths",Number(e.target.value))}/><TextField type="number" label="할인율 (%)" value={form.value} onChange={e=>set("value",Number(e.target.value))}/></>}{!["FREE_MONTHS","PERCENT_DISCOUNT"].includes(form.type)&&<TextField type="number" label="지급 횟수" value={form.value} onChange={e=>set("value",Number(e.target.value))}/>}<Stack direction="row" gap={1}><TextField fullWidth type="date" label="시작일" InputLabelProps={{shrink:true}} value={form.validFrom} onChange={e=>set("validFrom",e.target.value)}/><TextField fullWidth type="date" label="종료일" InputLabelProps={{shrink:true}} value={form.validUntil} onChange={e=>set("validUntil",e.target.value)}/></Stack>{form.distributionType==="SINGLE"&&<TextField type="number" label="생성 수량" value={form.quantity} onChange={e=>set("quantity",Number(e.target.value))}/>}</Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>취소</Button><Button variant="contained" onClick={save}>저장</Button></DialogActions></Dialog>
 <Dialog open={!!detail} onClose={()=>setDetail(null)} fullWidth><DialogTitle>사용 내역</DialogTitle><DialogContent>{detail?.redemptions.map(u=><Box key={u.id} py={1}><b>{u.name}</b> · {u.email}<br/><small>{new Date(u.redeemed_at).toLocaleString()}</small>{u.clubs.map(c=><Chip key={c.id} size="small" label={`클럽장 · ${c.name}`}/>)}</Box>)}</DialogContent></Dialog></Box>;
}
