import { useCallback, useEffect, useState } from "react";
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, Switch, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from "@mui/material";
const API=import.meta.env.VITE_API_BASE_URL??"/api";
const TYPES:Record<string,string>={FREE_MONTHS:"구독 N개월 무료",PERCENT_DISCOUNT:"구독 N% 할인",LEAGUE_CREATE:"리그 생성 N회",VISION_SCAN:"사진 인식 N회",DRAW_CREATE:"추첨 생성 N회"};
type Redemption={id:number;name:string;email:string;redeemed_at:string;clubs:Array<{id:string;name:string}>};
type Coupon={id:string;code:string;name:string;type:string;value:number;plan_code:string|null;valid_from:string;valid_until:string;is_active:boolean;distribution_type:"SINGLE"|"OPEN";max_redemptions:number|null;redemption_count:number;redemptions:Redemption[]};
const initial={name:"",type:"LEAGUE_CREATE",value:1,planCode:"",validFrom:new Date().toISOString().slice(0,10),validUntil:"",quantity:1,distributionType:"SINGLE",customCode:"",maxRedemptions:""};
export default function AdminCouponPage(){
 const token=localStorage.getItem("admin_token")??"",headers={"Content-Type":"application/json",Authorization:`Bearer ${token}`};
 const [rows,setRows]=useState<Coupon[]>([]),[search,setSearch]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState<Coupon|null>(null),[detail,setDetail]=useState<Coupon|null>(null),[form,setForm]=useState(initial),[error,setError]=useState("");
 const load=useCallback(async()=>{const r=await fetch(`${API}/admin/coupons?search=${encodeURIComponent(search)}`,{headers});const d=await r.json();r.ok?setRows(d.coupons??[]):setError("쿠폰 목록을 불러오지 못했습니다.");},[search]); useEffect(()=>{void load();},[load]);
 const edit=(c:Coupon)=>{setEditing(c);setForm({...initial,name:c.name,type:c.type,value:c.value,planCode:c.plan_code??"",validFrom:c.valid_from.slice(0,10),validUntil:c.valid_until.slice(0,10),distributionType:c.distribution_type,customCode:c.code,maxRedemptions:c.max_redemptions?.toString()??""});setOpen(true);};
 const save=async()=>{setError("");const r=await fetch(editing?`${API}/admin/coupons/${editing.id}`:`${API}/admin/coupons`,{method:editing?"PATCH":"POST",headers,body:JSON.stringify({...form,validFrom:new Date(`${form.validFrom}T00:00:00+09:00`).toISOString(),validUntil:new Date(`${form.validUntil}T23:59:59+09:00`).toISOString(),maxRedemptions:form.maxRedemptions||null})});const d=await r.json();if(!r.ok){setError(d.error==="DUPLICATE_CODE"?"이미 사용 중인 쿠폰번호입니다.":d.error==="USED_COUPON_IMMUTABLE"?"사용 이력이 있는 쿠폰은 수정할 수 없습니다.":"쿠폰을 저장하지 못했습니다.");return;}setOpen(false);await load();};
 const remove=async(c:Coupon)=>{if(!confirm(`${c.code} 쿠폰을 삭제하시겠습니까?`))return;await fetch(`${API}/admin/coupons/${c.id}`,{method:"DELETE",headers});await load();};
 const toggle=async(c:Coupon)=>{await fetch(`${API}/admin/coupons/${c.id}`,{method:"PATCH",headers,body:JSON.stringify({isActive:!c.is_active})});await load();};
 return <Box sx={{p:3}}><Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between" gap={1} mb={2}><Box><Typography fontSize={20} fontWeight={900}>쿠폰 관리</Typography><Typography fontSize={13} color="text.secondary">1회용 쿠폰과 SNS 공개용 오픈 쿠폰을 관리합니다.</Typography></Box><Button variant="contained" onClick={()=>{setEditing(null);setForm(initial);setOpen(true);}}>쿠폰 생성</Button></Stack>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<TextField fullWidth size="small" placeholder="쿠폰번호, 쿠폰명, 사용자 이메일 검색" value={search} onChange={e=>setSearch(e.target.value)} sx={{mb:2}}/>
 <TableContainer><Table size="small"><TableHead><TableRow><TableCell>쿠폰번호</TableCell><TableCell>발급</TableCell><TableCell>혜택</TableCell><TableCell>사용기한</TableCell><TableCell>상태 / 사용</TableCell><TableCell align="right">관리</TableCell></TableRow></TableHead><TableBody>{rows.map(c=><TableRow key={c.id} hover><TableCell><Typography fontFamily="monospace" fontWeight={800}>{c.code}</Typography><Typography fontSize={12}>{c.name}</Typography></TableCell><TableCell><Chip size="small" label={c.distribution_type==="OPEN"?"오픈":"1회용"} color={c.distribution_type==="OPEN"?"primary":"default"}/></TableCell><TableCell>{TYPES[c.type]} · {c.value}{c.type==="PERCENT_DISCOUNT"?"%":c.type==="FREE_MONTHS"?"개월":"회"}</TableCell><TableCell>{new Date(c.valid_from).toLocaleDateString("ko-KR")} ~ {new Date(c.valid_until).toLocaleDateString("ko-KR")}</TableCell><TableCell><Chip size="small" color={c.is_active?"success":"error"} label={c.is_active?"사용 가능":"중지"}/><Button size="small" onClick={()=>setDetail(c)}>{c.redemption_count}명{c.max_redemptions?` / ${c.max_redemptions}명`:""}</Button></TableCell><TableCell align="right"><Switch size="small" checked={c.is_active} onChange={()=>toggle(c)}/><Button size="small" disabled={c.redemption_count>0} onClick={()=>edit(c)}>수정</Button><Button size="small" color="error" onClick={()=>remove(c)}>삭제</Button></TableCell></TableRow>)}{!rows.length&&<TableRow><TableCell colSpan={6} align="center" sx={{py:6}}>등록된 쿠폰이 없습니다.</TableCell></TableRow>}</TableBody></Table></TableContainer>
 <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle fontWeight={900}>{editing?"쿠폰 수정":"쿠폰 생성"}</DialogTitle><DialogContent><Stack gap={2} mt={1}>{!editing&&<TextField select label="발급 방식" value={form.distributionType} onChange={e=>setForm({...form,distributionType:e.target.value})}><MenuItem value="SINGLE">1회용 난수 쿠폰</MenuItem><MenuItem value="OPEN">SNS 공개용 오픈 쿠폰</MenuItem></TextField>}{!editing&&form.distributionType==="OPEN"&&<><TextField label="공개 쿠폰번호" value={form.customCode} onChange={e=>setForm({...form,customCode:e.target.value})} helperText="한글·영문·숫자를 사용할 수 있습니다. 띄어쓰기·하이픈·영문 대소문자는 구분하지 않습니다."/><TextField type="number" label="전체 사용 한도 (비우면 무제한)" value={form.maxRedemptions} onChange={e=>setForm({...form,maxRedemptions:e.target.value})}/></>}<TextField label="쿠폰명" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><TextField select label="쿠폰 종류" disabled={!!editing} value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{Object.entries(TYPES).map(([v,l])=><MenuItem key={v} value={v}>{l}</MenuItem>)}</TextField><TextField type="number" label="혜택 수치" value={form.value} onChange={e=>setForm({...form,value:Number(e.target.value)})}/>{["FREE_MONTHS","PERCENT_DISCOUNT"].includes(form.type)&&<TextField label="적용 요금제 코드 (선택)" value={form.planCode} onChange={e=>setForm({...form,planCode:e.target.value})}/>}<Stack direction="row" gap={1}><TextField fullWidth type="date" label="시작일" InputLabelProps={{shrink:true}} value={form.validFrom} onChange={e=>setForm({...form,validFrom:e.target.value})}/><TextField fullWidth type="date" label="종료일" InputLabelProps={{shrink:true}} value={form.validUntil} onChange={e=>setForm({...form,validUntil:e.target.value})}/></Stack>{!editing&&form.distributionType==="SINGLE"&&<TextField type="number" label="생성 수량 (최대 100)" value={form.quantity} onChange={e=>setForm({...form,quantity:Number(e.target.value)})}/>}</Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>취소</Button><Button variant="contained" onClick={save}>저장</Button></DialogActions></Dialog>
 <Dialog open={!!detail} onClose={()=>setDetail(null)} fullWidth maxWidth="sm"><DialogTitle fontWeight={900}>{detail?.code} 사용 내역</DialogTitle><DialogContent>{detail?.redemptions.map(r=><Box key={r.id} sx={{py:1.5,borderBottom:"1px solid #eee"}}><Typography fontWeight={800}>{r.name||"이름 없음"} · {r.email}</Typography><Typography fontSize={12} color="text.secondary">{new Date(r.redeemed_at).toLocaleString("ko-KR")}</Typography>{r.clubs?.map(c=><Chip key={c.id} size="small" label={`클럽장 · ${c.name}`} sx={{mt:.5,mr:.5}}/>)}</Box>)}{!detail?.redemptions.length&&<Typography sx={{py:4,textAlign:"center"}}>아직 사용한 회원이 없습니다.</Typography>}</DialogContent><DialogActions><Button onClick={()=>setDetail(null)}>닫기</Button></DialogActions></Dialog></Box>;
}
