import { useState } from "react";
import { Box, Card, CardContent, Divider, IconButton, List, ListItem, ListItemText, Stack, Typography } from "@mui/material";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import EmojiEventsOutlinedIcon from "@mui/icons-material/EmojiEventsOutlined";
import { useNavigate } from "react-router-dom";
import { DEMO_CLUB_MEMBERS, DEMO_RANKINGS } from "./demoSampleData";

export default function DemoClubPage() {
  const navigate = useNavigate();
  const [rankingOpen, setRankingOpen] = useState(false);
  const memberById = new Map(DEMO_CLUB_MEMBERS.map((member) => [member.id, member]));

  if (rankingOpen) return <Stack spacing={2.2} sx={{ pb: 3 }}><Stack direction="row" alignItems="center" spacing={1}><IconButton onClick={() => setRankingOpen(false)} size="small"><ArrowBackIcon/></IconButton><Typography variant="h6" fontWeight={900}>우리리그 클럽 순위</Typography></Stack><Card elevation={2} sx={{ borderRadius: 1, boxShadow: "0 4px 12px rgba(0,0,0,0.08)" }}><List disablePadding><ListItem sx={{ display: "grid", gridTemplateColumns: "48px 1fr 72px 64px", py: 1.5, px: 2, bgcolor: "#f5f5f5" }}><Typography fontWeight={700} fontSize={13}>순위</Typography><Typography fontWeight={700} fontSize={13}>이름</Typography><Typography fontWeight={700} fontSize={13}>전적</Typography><Typography fontWeight={700} fontSize={13} textAlign="right">점수</Typography></ListItem>{DEMO_RANKINGS.map((row, index) => { const member = memberById.get(row.personId); return <Box key={row.personId}>{index > 0 && <Divider/>}<ListItem sx={{ display: "grid", gridTemplateColumns: "48px 1fr 72px 64px", py: 1.5, px: 2, bgcolor: row.rank <= 3 ? "rgba(255, 193, 7, 0.06)" : "transparent" }}><Typography fontWeight={900} color={row.rank <= 3 ? "#D97706" : "inherit"}>{row.rank}</Typography><Box><Typography fontWeight={800} fontSize={14}>{member?.name}</Typography><Typography fontSize={11} color="text.secondary">{member?.division}</Typography></Box><Typography fontWeight={700} fontSize={13}>{row.wins}승 {row.losses}패</Typography><Typography fontWeight={800} fontSize={13} textAlign="right">{row.rating}</Typography></ListItem></Box>; })}</List></Card><Typography textAlign="center" color="text.secondary" fontSize={12}>기능 소개를 위한 샘플 순위입니다.</Typography></Stack>;

  return <Stack spacing={2.5} sx={{ pb: 3 }}><Stack direction="row" alignItems="center" spacing={1.5}><IconButton onClick={() => navigate("/club")} size="small"><ArrowBackIcon/></IconButton><Typography variant="h6" fontWeight={900} flex={1}>클럽 정보</Typography></Stack>
    <Card elevation={2} sx={{ borderRadius: 1, boxShadow: "0 4px 12px rgba(0,0,0,0.08)" }}><CardContent sx={{ py: 2.5, px: 2.5, "&:last-child": { pb: 2.5 } }}><Stack spacing={2}><Stack direction="row" alignItems="center" spacing={2}><Typography sx={{ fontSize: 32, lineHeight: 1 }}>🏓</Typography><Box flex={1}><Typography fontWeight={900} fontSize={20}>우리리그 클럽</Typography><Typography fontSize={13} color="text.secondary" fontWeight={600}>서울 광진구</Typography></Box></Stack><Typography fontSize={14} color="text.secondary" sx={{ lineHeight: 1.7 }}>우리리그 클럽입니다.</Typography></Stack></CardContent></Card>
    <Box><Stack direction="row" alignItems="center" spacing={0.75} sx={{ mb: 1.5 }}><Typography variant="subtitle1" fontWeight={900} flex={1}>클럽 회원 ({DEMO_CLUB_MEMBERS.length}명)</Typography><IconButton size="small" onClick={() => setRankingOpen(true)} sx={{ color: "#D97706" }}><EmojiEventsOutlinedIcon/></IconButton></Stack><Card elevation={2} sx={{ borderRadius: 1, boxShadow: "0 4px 12px rgba(0,0,0,0.08)" }}><List disablePadding><ListItem sx={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", py: 1.5, px: 2.5, bgcolor: "#f5f5f5" }}><Typography fontWeight={700} fontSize={14}>구분</Typography><Typography fontWeight={700} fontSize={14}>부수</Typography><Typography fontWeight={700} fontSize={14}>이름</Typography></ListItem>{DEMO_CLUB_MEMBERS.map((member, index) => <Box key={member.id}>{index > 0 && <Divider/>}<ListItem sx={{ py: 1.5, px: 2.5, bgcolor: index === 0 ? "rgba(255, 193, 7, 0.08)" : index === 1 ? "rgba(33, 150, 243, 0.08)" : "transparent" }}><ListItemText sx={{ flex: 1 }} primary={<Typography fontWeight={700} fontSize={14}>{index === 0 ? "클럽장" : index === 1 ? "운영진" : "회원"}</Typography>}/><ListItemText sx={{ flex: 1 }} primary={<Typography fontWeight={700} fontSize={14}>{member.division}</Typography>}/><ListItemText sx={{ flex: 1 }} primary={<Typography fontWeight={700} fontSize={14}>{member.name}</Typography>}/></ListItem></Box>)}</List></Card></Box><Typography textAlign="center" color="text.secondary" fontSize={12}>실제 회원 정보가 아닌 체험용 샘플입니다.</Typography>
  </Stack>;
}
