import { useState } from "react";
import { Box, Button, Card, CardContent, Chip, Divider, FormControlLabel, IconButton, Radio, RadioGroup, Stack, TextField, Typography } from "@mui/material";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import { useNavigate } from "react-router-dom";
import { DEMO_BRACKET, DEMO_CUSTOM_PROGRAM, DEMO_LEAGUE, DEMO_MATCHES, DEMO_PEOPLE, DEMO_RECOMMENDED_PROGRAM } from "./demoSampleData";

const rowSx = { display: "grid", gridTemplateColumns: "72px 1fr", alignItems: "center", gap: 2, py: 1.2, borderBottom: "1px solid #D9DDE6" };
const fieldSx = { "& .MuiOutlinedInput-root": { borderRadius: 0.6, bgcolor: "#fff", minHeight: 32 }, "& .MuiOutlinedInput-input": { py: 0.5, fontSize: "0.95rem", WebkitTextFillColor: "#111827" } };
const navButtonSx = { height: 44, borderRadius: 1, fontWeight: 900 };
type View = "create" | "detail" | "matches" | "bracket";

function ProgramRows({ custom }: { custom: boolean }) {
  const items = custom ? DEMO_CUSTOM_PROGRAM : DEMO_RECOMMENDED_PROGRAM;
  return <Box sx={{ borderTop: "1px solid #D9DDE6" }}>{items.map((item) => <Box key={item.round} sx={{ py: 1.5, borderBottom: "1px solid #D9DDE6" }}><Typography fontSize={13} fontWeight={800} color="#2F80ED">{item.round}</Typography><Typography fontWeight={900} mt={0.3}>{item.program} · {item.format}</Typography><Typography fontSize={13} color="text.secondary" mt={0.4}>{item.detail}</Typography></Box>)}</Box>;
}

function Header({ title, back }: { title: string; back: () => void }) {
  return <Stack direction="row" alignItems="center" sx={{ mb: 2 }}><IconButton onClick={back} size="small" sx={{ mr: 0.5 }}><ArrowBackIcon /></IconButton><Typography fontWeight={900} fontSize={18}>{title}</Typography></Stack>;
}

function DemoLeagueDetail({ mode, onBack, onMatches, onBracket, onRestart }: { mode: "recommend" | "custom"; onBack: () => void; onMatches: () => void; onBracket: () => void; onRestart: () => void }) {
  const program = mode === "recommend" ? DEMO_RECOMMENDED_PROGRAM : DEMO_CUSTOM_PROGRAM;
  const [showAll, setShowAll] = useState(false);
  const visiblePeople = showAll ? DEMO_PEOPLE : DEMO_PEOPLE.slice(0, 6);
  void onRestart;
  return <Box sx={{ pb: 9 }}><Header title={DEMO_LEAGUE.name} back={onBack}/>
    <Box sx={{ bgcolor: "#fff", borderRadius: 1, border: "1px solid #D7DDE8", px: 1.5, py: 0.8, mb: 2 }}>
      {[["날 짜", DEMO_LEAGUE.date], ["시 간", DEMO_LEAGUE.time], ["장 소", DEMO_LEAGUE.location], ["코트", `${DEMO_LEAGUE.courtCount}`]].map(([label, value]) => <Box key={label}><Stack direction="row" alignItems="center" sx={{ py: 0.9 }}><Typography sx={{ width: 64, fontSize: 12, fontWeight: 900, color: "#6B7280", letterSpacing: 1 }}>{label}</Typography><Typography sx={{ fontSize: 12, fontWeight: 900 }}>{value}</Typography></Stack><Divider sx={{ borderColor: "#EEF0F4" }}/></Box>)}
      <Stack direction="row" alignItems="center" sx={{ py: 0.8 }}><Typography flex={1} sx={{ fontSize: 13, fontWeight: 900, color: "#6B7280" }}>프로그램</Typography><Button size="small" variant="outlined" sx={{ minWidth: 52, height: 30, borderRadius: 1, px: 1.4, fontSize: 12, fontWeight: 900 }}>수정</Button></Stack>
      <Stack spacing={1.2} sx={{ mb: 1.2 }}>{program.map((item) => <Box key={item.round} sx={{ border: "1px solid #E1E5EC", borderRadius: 2, p: 1.5, bgcolor: "#F8FAFC" }}><Stack direction="row" alignItems="center"><Typography fontSize={15} fontWeight={900} flex={1}>{item.round} {item.program}</Typography><Chip label={item.format} size="small" sx={{ height: 26, px: 0.4, fontSize: 11, fontWeight: 700, bgcolor: "#F3E8FF", color: "#7C3AED", border: "1px solid #E9D5FF" }}/></Stack><Stack direction="row" spacing={1.2} mt={1.2}><Button fullWidth variant="outlined" onClick={onMatches} sx={{ height: 46, borderRadius: 2, fontSize: 14, fontWeight: 900 }}>경기순서　〉</Button><Button fullWidth variant="contained" disableElevation onClick={onBracket} sx={{ height: 46, borderRadius: 2, fontSize: 14, fontWeight: 900 }}>대진표 보기　〉</Button></Stack></Box>)}</Stack>
      <Divider sx={{ borderColor: "#EEF0F4" }}/><Stack direction="row" alignItems="center" sx={{ py: 0.9 }}><Typography flex={1} fontSize={12} fontWeight={900}>참여 클럽</Typography><Button size="small" variant="outlined" sx={{ minWidth: 42, height: 24, borderRadius: 1, px: 1, fontSize: 11, fontWeight: 800 }}>관리</Button></Stack>
    </Box>
    <Box sx={{ mb: 1 }}><Stack direction="row" alignItems="center" mb={1}><Typography fontWeight={900} fontSize={15} flex={1}>참가자 <Typography component="span" fontSize={12} color="text.secondary">( 8명 )</Typography></Typography><Button size="small" variant="outlined" sx={{ height: 26, fontSize: 10, fontWeight: 800 }}>전환 신청</Button><Button size="small" variant="outlined" sx={{ height: 26, ml: 0.7, fontSize: 10, fontWeight: 800 }}>추가/삭제</Button></Stack><TextField fullWidth size="small" placeholder="이름 또는 부수 검색" sx={{ mb: 1, "& .MuiOutlinedInput-root": { height: 32, borderRadius: 1, fontSize: 12 } }}/>
      <Card elevation={0} sx={{ border: "1px solid #D7DDE8", borderRadius: 1 }}><Box sx={{ display: "grid", gridTemplateColumns: "54px 1fr 116px", bgcolor: "#F7F8FA", px: 1.2, py: 0.7 }}><Typography fontSize={10} fontWeight={800}>부수</Typography><Typography fontSize={10} fontWeight={800}>이름</Typography><Typography fontSize={10} fontWeight={800} textAlign="center">상태</Typography></Box>{visiblePeople.map((person, index) => <Box key={person.id}><Box sx={{ display: "grid", gridTemplateColumns: "54px 1fr 116px", alignItems: "center", px: 1.2, py: 0.55 }}><Box sx={{ width: 30, height: 30, borderRadius: "50%", bgcolor: "#FAAA47", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 900, fontSize: 10 }}>{person.division.replace("부", "")}</Box><Typography fontWeight={900} fontSize={12}>{person.name}</Typography><Stack direction="row" spacing={0.4} justifyContent="flex-end"><Chip label="입금" size="small" variant="outlined" sx={{ height: 20, fontSize: 9 }}/><Chip label="도착" size="small" variant="outlined" sx={{ height: 20, fontSize: 9 }}/><Chip label="뒷풀이" size="small" variant="outlined" sx={{ height: 20, fontSize: 9 }}/></Stack></Box>{index < visiblePeople.length - 1 && <Divider/>}</Box>)}{!showAll && <Button fullWidth onClick={() => setShowAll(true)} sx={{ height: 32, fontSize: 11, fontWeight: 900 }}>2명 더보기</Button>}</Card>
    </Box>
    <Button fullWidth variant="outlined" sx={{ height: 38, borderRadius: 1, fontWeight: 900, mb: 2 }}>경품 추첨</Button>
    <Typography fontWeight={900} fontSize={14} mb={0.7}>안내사항</Typography><TextField fullWidth multiline minRows={3} value="경기 시작 20분 전까지 도착해주세요." disabled sx={{ mb: 1.5, "& .MuiOutlinedInput-root": { borderRadius: 1, bgcolor: "#fff" }, "& .MuiInputBase-input.Mui-disabled": { WebkitTextFillColor: "#6B7280" } }}/>
    <Typography fontWeight={900} fontSize={14} mb={0.7}>참가비</Typography><TextField fullWidth value="10,000원" disabled sx={{ mb: 1.5, "& .MuiOutlinedInput-root": { height: 42, borderRadius: 1, bgcolor: "#fff" }, "& .MuiInputBase-input.Mui-disabled": { WebkitTextFillColor: "#111827", fontWeight: 700 } }}/>
    <Typography fontWeight={900} fontSize={14} mb={0.7}>입금 계좌</Typography><TextField fullWidth value="우리은행 000-0000-0000 (예금주: 우리리그) · 데모 계좌" disabled sx={{ mb: 1.5, "& .MuiOutlinedInput-root": { height: 42, borderRadius: 1, bgcolor: "#fff" }, "& .MuiInputBase-input.Mui-disabled": { WebkitTextFillColor: "#111827", fontWeight: 700, fontSize: 12 } }}/>
    <Button color="error" size="small" sx={{ justifyContent: "flex-start", px: 0, fontSize: 12, fontWeight: 800 }}>리그 삭제</Button>
    <Button fullWidth variant="contained" disableElevation sx={{ position: "fixed", bottom: "calc(56px + env(safe-area-inset-bottom))", left: "50%", transform: "translateX(-50%)", width: "min(calc(100% - 16px), 414px)", height: 42, zIndex: 5, borderRadius: 1, fontWeight: 900 }}>리그 시작</Button>
  </Box>;
}

export default function DemoLeaguePage() {
  const navigate = useNavigate();
  const [step, setStep] = useState(1);
  const [mode, setMode] = useState<"recommend" | "custom">("recommend");
  const [view, setView] = useState<View>("create");
  const back = () => view === "create" ? navigate("/league") : setView("detail");

  if (String(view) === "detail") return <DemoLeagueDetail mode={mode} onBack={() => navigate("/league")} onMatches={() => setView("matches")} onBracket={() => setView("bracket")} onRestart={() => { setStep(1); setView("create"); }}/>;

  if (view === "matches") return <Box sx={{ pb: 4 }}><Header title="경기순서" back={back}/><Stack spacing={1}>{DEMO_MATCHES.map((match) => <Card key={match.order} elevation={2} sx={{ borderRadius: 1, boxShadow: "0 4px 12px rgba(0,0,0,0.08)" }}><CardContent sx={{ py: 1.5, px: 1.8, "&:last-child": { pb: 1.5 } }}><Stack direction="row" alignItems="center"><Chip label={`${match.order}`} size="small" sx={{ height: 22, fontWeight: 800, bgcolor: "#EEF2FF", color: "#2F80ED", mr: 1 }}/><Typography fontWeight={900} fontSize={14} flex={1}>{match.court}</Typography><Chip label={match.status} size="small" color="success"/></Stack><Divider sx={{ my: 1 }}/><Stack direction="row" justifyContent="space-between"><Typography fontWeight={800}>{match.left}</Typography><Typography fontWeight={900} color="#2F80ED">{match.score}</Typography><Typography fontWeight={800}>{match.right}</Typography></Stack></CardContent></Card>)}</Stack><Typography color="text.secondary" fontSize={12} textAlign="center" mt={2}>데모 경기 결과는 조회만 가능합니다.</Typography></Box>;

  if (view === "bracket") return <Box sx={{ pb: 4 }}><Header title="토너먼트 대진표" back={back}/><Stack spacing={2}>{DEMO_BRACKET.map((match) => <Box key={match.label} sx={{ bgcolor: "#fff", border: "1px solid #E5E7EB", borderRadius: 1, p: 2 }}><Typography fontSize={12} fontWeight={900} color="#2F80ED">{match.label}</Typography><Stack direction="row" alignItems="center" justifyContent="space-between" mt={1.2}><Typography fontWeight={match.winner === match.left ? 900 : 600}>{match.left}</Typography><Chip label={match.score} size="small"/><Typography fontWeight={match.winner === match.right ? 900 : 600}>{match.right}</Typography></Stack></Box>)}<Card elevation={2} sx={{ borderRadius: 1 }}><CardContent sx={{ textAlign: "center" }}><Typography fontSize={13} color="text.secondary" fontWeight={700}>우승</Typography><Typography fontSize={22} color="#2F80ED" fontWeight={900} mt={0.5}>김민준</Typography></CardContent></Card></Stack></Box>;

  if (view === "detail") return <Box sx={{ pb: 4 }}><Header title={DEMO_LEAGUE.name} back={() => navigate("/league")}/><Box sx={{ bgcolor: "#fff", borderRadius: 1, border: "1px solid #E5E7EB", px: 2, py: 1, mb: 2.5 }}>{[["날 짜", DEMO_LEAGUE.date], ["시 간", DEMO_LEAGUE.time], ["장 소", DEMO_LEAGUE.location], ["코트", `${DEMO_LEAGUE.courtCount}`], ["유 형", "이벤트 프로그램"], ["방 식", mode === "recommend" ? "추천 프로그램" : "직접 구성"]].map(([label, value], index) => <Box key={label}><Stack direction="row" alignItems="center" sx={{ py: 1.1 }}><Typography sx={{ width: 76, fontSize: 13, fontWeight: 800, color: "#6B7280" }}>{label}</Typography><Typography sx={{ fontSize: 13, fontWeight: 800 }}>{value}</Typography></Stack>{index < 5 && <Divider sx={{ borderColor: "#F3F4F6" }}/>}</Box>)}</Box><Box sx={{ mb: 2.5 }}><Stack direction="row" alignItems="center" mb={1}><Typography fontWeight={900} fontSize={16} flex={1}>참가자 <Typography component="span" fontSize={13} color="text.secondary">( 8명 )</Typography></Typography></Stack><Card elevation={2} sx={{ borderRadius: 1, boxShadow: "0 4px 12px rgba(0,0,0,0.08)" }}><Box sx={{ display: "grid", gridTemplateColumns: "72px 1fr", bgcolor: "#f5f5f5", px: 2.5, py: 1.3 }}><Typography fontWeight={700} fontSize={14}>부수</Typography><Typography fontWeight={700} fontSize={14}>이름</Typography></Box>{DEMO_PEOPLE.map((person, index) => <Box key={person.id}><Stack direction="row" sx={{ px: 2.5, py: 1.3 }}><Typography width={72} fontWeight={700} fontSize={14}>{person.division}</Typography><Typography fontWeight={700} fontSize={14}>{person.name}</Typography></Stack>{index < DEMO_PEOPLE.length - 1 && <Divider/>}</Box>)}</Card></Box><Stack spacing={1}><Button fullWidth variant="outlined" sx={{ borderRadius: 1, fontWeight: 800 }} onClick={() => setView("matches")}>경기순서 보기</Button><Button fullWidth variant="outlined" sx={{ borderRadius: 1, fontWeight: 800 }} onClick={() => setView("bracket")}>토너먼트 대진표 보기</Button><Button fullWidth variant="contained" sx={{ borderRadius: 1, fontWeight: 800 }} onClick={() => { setStep(1); setView("create"); }}>리그 생성 다시 체험</Button></Stack></Box>;

  return <Box sx={{ px: 2.5, pt: 2, pb: 4 }}>{step !== 4 && <Typography sx={{ fontSize: 22, fontWeight: 900, mb: 2 }}>{step === 1 ? "리그 정보" : step === 2 ? "리그 구성" : "프로그램 선택"}</Typography>}
    {step === 1 && <Box sx={{ borderTop: "1px solid #D9DDE6" }}>{[["리그명", DEMO_LEAGUE.name], ["날짜", "2026-01-01"], ["시간", "09:00 ~ 18:00"], ["장소", DEMO_LEAGUE.location], ["코트 수", "4"], ["참가자 수", "8"]].map(([label, value]) => <Box key={label} sx={rowSx}><Typography fontWeight={900}>{label}</Typography><TextField value={value} disabled size="small" sx={fieldSx}/></Box>)}</Box>}
    {step === 2 && <RadioGroup value={mode} onChange={(event) => setMode(event.target.value as "recommend" | "custom")}><Stack spacing={1.5}>{[{ value: "recommend", title: "추천 프로그램", description: "참가자 수와 운영 시간을 기준으로 자동 추천된 프로그램입니다." }, { value: "custom", title: "직접 구성하기", description: "단식, 복식, 단체전을 라운드별로 구성한 프로그램입니다." }].map((choice) => <FormControlLabel key={choice.value} value={choice.value} control={<Radio/>} label={<Box><Typography fontWeight={900}>{choice.title}</Typography><Typography mt={0.5} color="text.secondary" fontSize={14}>{choice.description}</Typography></Box>} sx={{ m: 0, minHeight: 104, px: 2, border: "1px solid", borderColor: mode === choice.value ? "#2F80ED" : "#D9DDE6", borderRadius: 1, bgcolor: mode === choice.value ? "#EFF6FF" : "#fff" }}/>)}</Stack></RadioGroup>}
    {step === 3 && <ProgramRows custom={mode === "custom"}/>}
    {step === 4 && <><Stack direction="row" alignItems="baseline" spacing={1} mb={1}><Typography fontSize={22} fontWeight={900}>참가자 사전 등록</Typography><Typography fontSize={14} fontWeight={700} color="#E53935">8/8</Typography></Stack><Divider sx={{ mb: 1.2, borderColor: "#D9DDE6" }}/><Box sx={{ display: "grid", gridTemplateColumns: "56px minmax(0,1fr) 56px", gap: 1, alignItems: "center", px: 0.5, mb: 0.8 }}><Typography textAlign="center" fontSize={12} fontWeight={900} color="#6B7280">부수</Typography><Typography textAlign="center" fontSize={12} fontWeight={900} color="#6B7280">이름</Typography><Typography textAlign="center" fontSize={12} fontWeight={900} color="#6B7280">관리</Typography></Box><Box sx={{ borderTop: "1px solid #D9DDE6", borderBottom: "1px solid #D9DDE6" }}>{DEMO_PEOPLE.map((person, index) => <Box key={person.id} sx={{ display: "grid", gridTemplateColumns: "56px minmax(0,1fr) 56px", gap: 1, alignItems: "center", px: 0.5, py: 0.6, borderTop: index ? "1px solid #ECEFF5" : 0 }}><Box sx={{ width: 36, height: 36, borderRadius: "50%", bgcolor: "#FAAA47", display: "flex", alignItems: "center", justifyContent: "center", justifySelf: "center", fontWeight: 900, fontSize: 11 }}>{person.division}</Box><Typography sx={{ fontWeight: 900, fontSize: 16, lineHeight: 1.1 }}>{person.name}</Typography><Button disabled variant="contained" disableElevation sx={{ borderRadius: 1, height: 28, minWidth: 48, p: 0, fontWeight: 900, bgcolor: "#D1D5DB", color: "#9CA3AF" }}>삭제</Button></Box>)}</Box></>}
    <Stack direction="row" spacing={2} sx={{ mt: 4 }}><Button fullWidth variant="contained" onClick={() => step === 1 ? navigate("/league") : setStep(step - 1)} sx={{ ...navButtonSx, bgcolor: "#777", "&:hover": { bgcolor: "#777" } }}>이전</Button><Button fullWidth variant="contained" onClick={() => step === 4 ? setView("detail") : setStep(step + 1)} sx={{ ...navButtonSx, bgcolor: "#2F80ED" }}>{step === 4 ? "완료" : "다음"}</Button></Stack>
    <Typography textAlign="center" color="text.secondary" fontSize={12} mt={2}>샘플 데이터는 수정할 수 없습니다.</Typography>
  </Box>;
}
