import { useState } from "react";
import { Box, Button, Card, CardContent, Chip, Divider, FormControlLabel, IconButton, Radio, RadioGroup, Stack, TextField, Typography } from "@mui/material";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import { useNavigate } from "react-router-dom";
import { DEMO_BRACKET, DEMO_CUSTOM_PROGRAM, DEMO_LEAGUE, DEMO_MATCHES, DEMO_PEOPLE, DEMO_RECOMMENDED_PROGRAM } from "./demoSampleData";

const rowSx = { display: "grid", gridTemplateColumns: "72px 1fr", alignItems: "center", gap: 2, py: 1.2, borderBottom: "1px solid #D9DDE6" };
const fieldSx = { "& .MuiOutlinedInput-root": { borderRadius: 0.6, bgcolor: "#fff", minHeight: 32 }, "& .MuiOutlinedInput-input": { py: 0.5, fontSize: "0.95rem", WebkitTextFillColor: "#111827" } };
const navButtonSx = { height: 44, borderRadius: 1, fontWeight: 900 };
type View = "create" | "detail" | "matches" | "bracket";

function ProgramRows({ custom }: { custom: boolean }) {
  const items = custom ? DEMO_CUSTOM_PROGRAM : DEMO_RECOMMENDED_PROGRAM;
  return <Box sx={{ borderTop: "1px solid #D9DDE6" }}>{items.map((item) => <Box key={item.round} sx={{ py: 1.5, borderBottom: "1px solid #D9DDE6" }}><Typography fontSize={13} fontWeight={800} color="#2F80ED">{item.round}</Typography><Typography fontWeight={900} mt={0.3}>{item.program} · {item.format}</Typography><Typography fontSize={13} color="text.secondary" mt={0.4}>{item.detail}</Typography></Box>)}</Box>;
}

function Header({ title, back }: { title: string; back: () => void }) {
  return <Stack direction="row" alignItems="center" sx={{ mb: 2 }}><IconButton onClick={back} size="small" sx={{ mr: 0.5 }}><ArrowBackIcon /></IconButton><Typography fontWeight={900} fontSize={18}>{title}</Typography></Stack>;
}

export default function DemoLeaguePage() {
  const navigate = useNavigate();
  const [step, setStep] = useState(1);
  const [mode, setMode] = useState<"recommend" | "custom">("recommend");
  const [view, setView] = useState<View>("create");
  const back = () => view === "create" ? navigate("/league") : setView("detail");

  if (view === "matches") return <Box sx={{ pb: 4 }}><Header title="경기순서" back={back}/><Stack spacing={1}>{DEMO_MATCHES.map((match) => <Card key={match.order} elevation={2} sx={{ borderRadius: 1, boxShadow: "0 4px 12px rgba(0,0,0,0.08)" }}><CardContent sx={{ py: 1.5, px: 1.8, "&:last-child": { pb: 1.5 } }}><Stack direction="row" alignItems="center"><Chip label={`${match.order}`} size="small" sx={{ height: 22, fontWeight: 800, bgcolor: "#EEF2FF", color: "#2F80ED", mr: 1 }}/><Typography fontWeight={900} fontSize={14} flex={1}>{match.court}</Typography><Chip label={match.status} size="small" color="success"/></Stack><Divider sx={{ my: 1 }}/><Stack direction="row" justifyContent="space-between"><Typography fontWeight={800}>{match.left}</Typography><Typography fontWeight={900} color="#2F80ED">{match.score}</Typography><Typography fontWeight={800}>{match.right}</Typography></Stack></CardContent></Card>)}</Stack><Typography color="text.secondary" fontSize={12} textAlign="center" mt={2}>데모 경기 결과는 조회만 가능합니다.</Typography></Box>;

  if (view === "bracket") return <Box sx={{ pb: 4 }}><Header title="토너먼트 대진표" back={back}/><Stack spacing={2}>{DEMO_BRACKET.map((match) => <Box key={match.label} sx={{ bgcolor: "#fff", border: "1px solid #E5E7EB", borderRadius: 1, p: 2 }}><Typography fontSize={12} fontWeight={900} color="#2F80ED">{match.label}</Typography><Stack direction="row" alignItems="center" justifyContent="space-between" mt={1.2}><Typography fontWeight={match.winner === match.left ? 900 : 600}>{match.left}</Typography><Chip label={match.score} size="small"/><Typography fontWeight={match.winner === match.right ? 900 : 600}>{match.right}</Typography></Stack></Box>)}<Card elevation={2} sx={{ borderRadius: 1 }}><CardContent sx={{ textAlign: "center" }}><Typography fontSize={13} color="text.secondary" fontWeight={700}>우승</Typography><Typography fontSize={22} color="#2F80ED" fontWeight={900} mt={0.5}>김민준</Typography></CardContent></Card></Stack></Box>;

  if (view === "detail") return <Box sx={{ pb: 4 }}><Header title={DEMO_LEAGUE.name} back={() => navigate("/league")}/><Box sx={{ bgcolor: "#fff", borderRadius: 1, border: "1px solid #E5E7EB", px: 2, py: 1, mb: 2.5 }}>{[["날 짜", DEMO_LEAGUE.date], ["시 간", DEMO_LEAGUE.time], ["장 소", DEMO_LEAGUE.location], ["탁구대", `${DEMO_LEAGUE.courtCount}대`], ["유 형", "이벤트 프로그램"], ["방 식", mode === "recommend" ? "추천 프로그램" : "직접 구성"]].map(([label, value], index) => <Box key={label}><Stack direction="row" alignItems="center" sx={{ py: 1.1 }}><Typography sx={{ width: 76, fontSize: 13, fontWeight: 800, color: "#6B7280" }}>{label}</Typography><Typography sx={{ fontSize: 13, fontWeight: 800 }}>{value}</Typography></Stack>{index < 5 && <Divider sx={{ borderColor: "#F3F4F6" }}/>}</Box>)}</Box><Box sx={{ mb: 2.5 }}><Stack direction="row" alignItems="center" mb={1}><Typography fontWeight={900} fontSize={16} flex={1}>참가자 <Typography component="span" fontSize={13} color="text.secondary">( 8명 )</Typography></Typography></Stack><Card elevation={2} sx={{ borderRadius: 1, boxShadow: "0 4px 12px rgba(0,0,0,0.08)" }}><Box sx={{ display: "grid", gridTemplateColumns: "72px 1fr", bgcolor: "#f5f5f5", px: 2.5, py: 1.3 }}><Typography fontWeight={700} fontSize={14}>부수</Typography><Typography fontWeight={700} fontSize={14}>이름</Typography></Box>{DEMO_PEOPLE.map((person, index) => <Box key={person.id}><Stack direction="row" sx={{ px: 2.5, py: 1.3 }}><Typography width={72} fontWeight={700} fontSize={14}>{person.division}</Typography><Typography fontWeight={700} fontSize={14}>{person.name}</Typography></Stack>{index < DEMO_PEOPLE.length - 1 && <Divider/>}</Box>)}</Card></Box><Stack spacing={1}><Button fullWidth variant="outlined" sx={{ borderRadius: 1, fontWeight: 800 }} onClick={() => setView("matches")}>경기순서 보기</Button><Button fullWidth variant="outlined" sx={{ borderRadius: 1, fontWeight: 800 }} onClick={() => setView("bracket")}>토너먼트 대진표 보기</Button><Button fullWidth variant="contained" sx={{ borderRadius: 1, fontWeight: 800 }} onClick={() => { setStep(1); setView("create"); }}>리그 생성 다시 체험</Button></Stack></Box>;

  return <Box sx={{ px: 0.5, pt: 0.5, pb: 4 }}><Header title={step === 1 ? "리그 정보" : step === 2 ? "리그 구성" : step === 3 ? "프로그램 선택" : "참가자 사전 등록"} back={() => step === 1 ? navigate("/league") : setStep(step - 1)}/>
    {step === 1 && <Box sx={{ borderTop: "1px solid #D9DDE6" }}>{[["리그명", DEMO_LEAGUE.name], ["날짜", "2026-01-01"], ["시간", "09:00 ~ 18:00"], ["장소", DEMO_LEAGUE.location], ["탁구대 수", "4대"], ["참가자 수", "8명"]].map(([label, value]) => <Box key={label} sx={rowSx}><Typography fontWeight={900}>{label}</Typography><TextField value={value} disabled size="small" sx={fieldSx}/></Box>)}</Box>}
    {step === 2 && <RadioGroup value={mode} onChange={(event) => setMode(event.target.value as "recommend" | "custom")}><Stack spacing={1.5}>{[{ value: "recommend", title: "추천 프로그램", description: "참가자 수와 운영 시간을 기준으로 자동 추천된 프로그램입니다." }, { value: "custom", title: "직접 구성하기", description: "단식, 복식, 단체전을 라운드별로 구성한 프로그램입니다." }].map((choice) => <FormControlLabel key={choice.value} value={choice.value} control={<Radio/>} label={<Box><Typography fontWeight={900}>{choice.title}</Typography><Typography mt={0.5} color="text.secondary" fontSize={14}>{choice.description}</Typography></Box>} sx={{ m: 0, minHeight: 104, px: 2, border: "1px solid", borderColor: mode === choice.value ? "#2F80ED" : "#D9DDE6", borderRadius: 1, bgcolor: mode === choice.value ? "#EFF6FF" : "#fff" }}/>)}</Stack></RadioGroup>}
    {step === 3 && <ProgramRows custom={mode === "custom"}/>}
    {step === 4 && <><Stack direction="row" alignItems="baseline" spacing={1} mb={1}><Typography fontSize={22} fontWeight={900}>참가자 사전 등록</Typography><Typography fontSize={14} fontWeight={700} color="#E53935">8/8</Typography></Stack><Divider sx={{ mb: 1.2 }}/><Box sx={{ display: "grid", gridTemplateColumns: "56px 1fr 56px", px: 0.5, mb: 0.8 }}><Typography textAlign="center" fontSize={12} fontWeight={900} color="#6B7280">부수</Typography><Typography textAlign="center" fontSize={12} fontWeight={900} color="#6B7280">이름</Typography><Typography textAlign="center" fontSize={12} fontWeight={900} color="#6B7280">관리</Typography></Box><Box sx={{ borderTop: "1px solid #D9DDE6", borderBottom: "1px solid #D9DDE6" }}>{DEMO_PEOPLE.map((person, index) => <Box key={person.id} sx={{ display: "grid", gridTemplateColumns: "56px 1fr 56px", alignItems: "center", px: 0.5, py: 0.6, borderTop: index ? "1px solid #ECEFF5" : 0 }}><Box sx={{ minWidth: 36, height: 36, px: 0.8, borderRadius: 9999, bgcolor: "#FAAA47", display: "inline-flex", alignItems: "center", justifyContent: "center", fontWeight: 900, fontSize: 11 }}>{person.division}</Box><Typography fontWeight={900} fontSize={16}>{person.name}</Typography><Button disabled variant="contained" sx={{ height: 28, minWidth: 48, p: 0, fontWeight: 900 }}>삭제</Button></Box>)}</Box></>}
    <Stack direction="row" spacing={2} sx={{ mt: 4 }}><Button fullWidth variant="contained" onClick={() => step === 1 ? navigate("/league") : setStep(step - 1)} sx={{ ...navButtonSx, bgcolor: "#777", "&:hover": { bgcolor: "#777" } }}>이전</Button><Button fullWidth variant="contained" onClick={() => step === 4 ? setView("detail") : setStep(step + 1)} sx={{ ...navButtonSx, bgcolor: "#2F80ED" }}>{step === 4 ? "완료" : "다음"}</Button></Stack>
    <Typography textAlign="center" color="text.secondary" fontSize={12} mt={2}>샘플 데이터는 수정할 수 없습니다.</Typography>
  </Box>;
}
